/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_march_fas_FFmpegSupport */

#ifndef _Included_com_march_fas_FFmpegSupport
#define _Included_com_march_fas_FFmpegSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_march_fas_FFmpegSupport
 * Method:    ffmpegRun
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_march_fas_FFmpegSupport_ffmpegRun
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
